---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cleanb-front-secret
  namespace: default
spec:
  encryptedData:
    NEXT_PUBLIC_API_URL: AgAiBrv+VxIxGu+go8InQMFA9dQM0c6pSM2x9j7eDGhkk5FhZuqE/NX4AyV8M7EyLU7MSnp+jN9ZacYbPP+9h+v3wmndNoOEWA8n3bh7dm+pCoWhZ3/EgT2RPK2ibm8+h7SVjjD22iBMwW/dsR3lTB7V+aVa7lh4jWZig96wiSp+YL0FKQnH2gGXsAoL+/2XM5Ztf/iVJZDARD2Ef7L6X+D+XKZyyfo/YFRnVsrJPOgljJISEphfZ6Jg0KwWT2bDDBwANs8Tw52EesSUammrFe8XTlhkZISLVE9nEnZSvP+1X/dRl9uNZa972iEIpRMgCy89UKGcz5oUFZUVD91FwyqDkYNNKSmvVVeLHWy8lE9EQHpoeeax+hwyq5SNSgw14AT0KzXgtMJfiDUH0YQFdQ5U+yE2edvKTDbeu/uPX6zM9cdNXwgmMXoeW0QgcIFFBgpK0oe/ntBOjuOh/FR3MlXRnVs6f3D+UNqGEfsdndqRmWcO94jSZwq0IGQJJ68WgvTJGGQTcQ3+YLQj2yx1G0e2nBXK7sgsdxvj7lZlQR4P/b2AKbRY7HqPaQoEzO3jCn8UJJCevnbyE8+GYnBOdWSuKri3r46Mv4MvS8H2HaGGIv+Ilx0kzTfzEa50EJ1H44O6bULIcKdTf/1+cy2oPupZ5AXXkHakDyEDQJm/zeJy25ksvmH7NJnIR5Hl0SERc8gnM4U2RDQOsPnl5weVvdpYzN3VltiaEWrUgfQVAQ==
  template:
    metadata:
      name: cleanb-front-secret
      namespace: default
    type: Opaque
