---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cleanb-front-secret
  namespace: default
spec:
  encryptedData:
    NEXT_PUBLIC_API_URL: AgAmcWZVWlVczb795LvoDpwhe97W3COwkhtnvBNkc79l6oihJjLeek95EoL8dONmHOqSwZM7TU2PQWDmhzWW5sCYCsijIjqOtYU90KJNsbrHz9VzV2UQ0wvu2yxUv7/QVLXUvNNdBdU0QFunQR3r+BLMJtZq4LUqP1reYYULm9dmPo6D78TEb7BSEhZHmNPhNz2Yq7KHAonoRAjGql1FkpT0JG33vj6v3x2U/R5pWBmpsvqKivD75mzoW3Gog62bD3aAFerXijc3sKOOCIK6gKcJyeBYlucISk96pzwArYN79Og4Im/hMiPaZ17FZbtx6Cbdtea+CAVwteeb6YEf3Ll+pEcTpgTCh2dIwMSr9cNQAgjm4g7UMbXIXmE9kCqpS++lL+YzpCLu0MaFTUUOwSNCUvHzLs5MPwcFRmceO5M4SPL2Q0yC11yLfiIU5Umhm3zL5ys2RtBzqxzL9f2VWPfCCvwfIO9H24GWO9j6tHX/vxUvjKP9OvYjiEMG4YtNWenPxXx/i/MHTP9ggwNPrMmi6MtaljET6PllQhoGCHaSYUVAOX863r+GPSXy4XrKcO9GYaYmkq1M/vXOhMmg87f7F0qFANSUfDyZfliw3DXXvbXMVbaAU8v3jd32SsuTRelxHNaO7lv/g+dotZI5KthNsjyAzrUpaWbpbitX4xj4fh8y+Yd5oH2Avv9QseqP4L3oOUZxrxmfkD0DnRfgdqie/lhLFXx6c5T1
  template:
    metadata:
      name: cleanb-front-secret
      namespace: default
    type: Opaque
