apiVersion: v1
kind: Service
metadata:
  name: cleanb-front-service
  labels:
    app: cleanb-front
spec:
  type: ClusterIP  # 내부 통신만 필요한 경우 ClusterIP, 외부 노출이 필요한 경우 NodePort 또는 LoadBalancer
  selector:
    app: cleanb-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
